name: schoolsystem
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logoph3.png
    - assets/images/discipline.png
    - assets/images/schedules.png
    - assets/images/calendar.png
    - assets/images/bulletins.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.otf
        - asset: assets/fonts/Poppins-Bold.otf
        - asset: assets/fonts/Poppins-ExtraBold.otf
        - asset: assets/fonts/Poppins-ExtraLight.otf
        - asset: assets/fonts/Poppins-Italic.otf
        - asset: assets/fonts/Poppins-Light.otf
        - asset: assets/fonts/Poppins-Medium.otf
        - asset: assets/fonts/Poppins-Regular.otf
        - asset: assets/fonts/Poppins-SemiBold.otf
        - asset: assets/fonts/Poppins-Thin.otf
